#pragma config(Motor,  port2,           left1,         tmotorServoContinuousRotation, openLoop, driveLeft)
#pragma config(Motor,  port3,           left2,         tmotorServoContinuousRotation, openLoop, driveLeft)
#pragma config(Motor,  port4,           right1,        tmotorServoContinuousRotation, openLoop, reversed, driveRight)
#pragma config(Motor,  port5,           right2,        tmotorServoContinuousRotation, openLoop, reversed, driveRight)
#pragma DebuggerWindows("DebugStream")

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task rx2;

short locationx;
int leftspeed;
int rightspeed;
char receivedline[100];
int pixysignature = 0;
int pixyx = 0;
int pixyy = 0;
int pixyw = 0;
int pixyh = 0;


void goforward(){
	leftspeed = 50;
	rightspeed = 50;
}

void gostop(){
	leftspeed = 0;
	rightspeed = 0;
}

void turnleft(){
	leftspeed = 0;
	rightspeed = 50;
}

void turnright(){
	leftspeed = 50;
	rightspeed = 0;
}

void go(){
	motor[left1] = leftspeed;
	motor[left2] = leftspeed;
	motor[right1] = rightspeed;
	motor[right2] = rightspeed;
}

void rx()
{
	locationx = getChar(uartOne);
	writeDebugStreamLine("Value: %d", locationx);
	sleep(20);
}

task rx2()
{
	while(true){
		static int rcvchar = getChar(uartOne);
		if(rcvchar == -1){
			wait1Msec(3);
			continue;
		}
		else{
			char rcvbyte = rcvchar;
			for(int c = 99; c>=0; c--){
				if(receivedline[c]!=0){
					receivedline[c+1] = rcvbyte;
					break;
				}
			}
			byte sync1 = 0xaa;
			byte sync2 = 0x55;
			string sync = "ªU";
			string mockrcv;
			stringFromChars(mockrcv,receivedline);
			int syncindex = stringFind(mockrcv,sync);
			if(syncindex != -1){
				byte pixydata[12];
				for(int a = syncindex-12; a<syncindex; a++){
					pixydata[a] = receivedline[a];
				}
				pixysignature = pixydata[2]*256 + pixydata[3];
				pixyx = pixydata[4]*256 + pixydata[5];
				pixyy = pixydata[6]*256 + pixydata[7];
				pixyw = pixydata[8]*256 + pixydata[9];
				pixyh = pixydata[10]*256 + pixydata[11];
				for(int b = 0; b< 50; b++){
					receivedline[b] = receivedline[syncindex+2+b];
				}
			}
		}
	}
}



task main()
{
	configureSerialPort(uartOne, uartUserControl);
	//setBaudRate(uartOne, baudRate19200);
	setBaudRate(uartOne, baudRate9600);
	//startTask(rx2);
	clearDebugStream();
	while (1){
		rx();
		//locationx = pixyx;
		writeDebugStreamLine("Value: %d", locationx);
		if(locationx != -1){

			//leftspeed = (locationx-80)+30;
			//rightspeed = (80+locationx)+30;

			if(locationx > 85){
				turnright();
			}
			else if (locationx < 75){
				turnleft();
			}
			else{
				goforward();
			}
		}else{
			gostop();
		}
		go();
	}
	/*while(1){
		goforward();
		go();
		wait1Msec(1000);
		turnleft();
		go();
		wait1Msec(1000);
		turnright();
		go();
		wait1Msec(1000);
	}*/
}
