#pragma config(Motor,  port2,           left1,         tmotorServoContinuousRotation, openLoop, driveLeft)
#pragma config(Motor,  port3,           left2,         tmotorServoContinuousRotation, openLoop, driveLeft)
#pragma config(Motor,  port4,           right1,        tmotorServoContinuousRotation, openLoop, driveRight)
#pragma config(Motor,  port5,           right2,        tmotorServoContinuousRotation, openLoop, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define joystickthreshold 15

//Config
bool auto = false;
bool mecanum = true;


//Channel
int x1 = 0;
int y1 = 0;
int x2 = 0;
int y2 = 0;

//Speed of each motor
int leftspeed[2];
int rightspeed[2];

//Debug String
string debugger;

void filterRT()	//Filter out noise in vexRT
{
	x1 = vexRT[Ch4];
	y1 = vexRT[Ch3];
	x2 = vexRT[Ch2];
	y2 = vexRT[Ch1];
	if(abs(x1) <= joystickthreshold)
	{
		x1 = 0;
	}
	if(abs(y1) <= joystickthreshold)
	{
		y1 = 0;
	}
	if(abs(x2) <= joystickthreshold)
	{
		x2 = 0;
	}
	if(abs(y2) <= joystickthreshold)
	{
		y2 = 0;
	}
}

void mecanumdrive()	//Using mecanumdrive
{
	leftspeed[0] = y1 + x2 + x1;
	leftspeed[1] = y1 + x2 - x1;
	rightspeed[0] = y1 - x2 - x1;
	rightspeed[1] = y1 - x2 + x1;
}

void skiddrive()	//Using skiddrive
{
	leftspeed[0] = y1 + x2;
	leftspeed[1] = y1 + x2;
	rightspeed[0] = y1 - x2;
	rightspeed[1] = y1 - x2;
}

void go()	//Runs the motor
{
	motor[left1] = leftspeed[0];
	motor[left2] = leftspeed[1];
	motor[right1] = rightspeed[0];
	motor[right2] = rightspeed[1];
}

void debugprint()	//Print debug info to LCD screen
{
	sprintf(debugger, "X1: %d, Y1: %d, X2: %d, Y2: %d", x1, y1, x2, y2);
	displayNextLCDString(debugger);
}

task main()
{
	while(!auto)
	{
		debugprint();
		filterRT();
		if(mecanum)
		{
			mecanumdrive();
		}
		else
		{
			skiddrive();
		}
		go();
	}
	while(auto)
	{
		//Auto function
	}
}
