void intake();
void outthrow();
void raisearm();
void putdownarm();
void takecone();
void releasecone();
void goforward();
void turn90(bool right);
void filterRT();
void mecanumdrive();
void skiddrive();
void go();
void debugprint();
