#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    mainliftpot,    sensorPotentiometer)
#pragma config(Sensor, in2,    secondaryliftpot, sensorPotentiometer)
#pragma config(Sensor, in3,    intakelevelpot, sensorPotentiometer)
#pragma config(Sensor, in5,    elbowpot,       sensorPotentiometer)
#pragma config(Sensor, dgtl2,  expandtouch,    sensorTouch)
#pragma config(Sensor, dgtl4,  intaketouch,    sensorTouch)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port2,           left,          tmotorVex393_MC29, PIDControl, driveLeft, encoderPort, I2C_1)
#pragma config(Motor,  port3,           right,         tmotorVex393_MC29, PIDControl, reversed, driveRight, encoderPort, I2C_2)
#pragma config(Motor,  port4,           mainlift,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           secondarylift, tmotorVex393_MC29, openLoop, encoderPort, None)
#pragma config(Motor,  port6,           mobileloader1, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           mobileloader2, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           elbow,         tmotorVex393_MC29, openLoop, encoderPort, I2C_3)
#pragma config(Motor,  port9,           intakelevel,   tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//main top 2500 bottom(starting) 3590
//secondary down 4010 up 250
//elbow down 0 up 710 releasecone -300

//1. mainpos -> 3370 (up)
//2. secondary -> 3950 (down)
//3. init autolevel

//take

//1.

#define raisearmbtn vexRT[Btn5U]
#define intakebtn vexRT[Btn6U]
#define debugautobtn vexRT[Btn7L]
#define waitbtn vexRT[Btn8U]
#define grabbtn vexRT[Btn8R]

#define joystickthreshold 15
#define mobileloaderdelay 50
#define elbowrev 100

int leftspeed;
int rightspeed;

int x1;
int y1;
int x2;
int y2;

//Last button state
bool lastraisearmbtn = false;
bool lastintakebtn = false;
bool lastdebugautobtn = false;
bool lastwaitbtn = false;
bool lastgrabbtn = false;
bool lastsecondaryupbtn = false;

//Button press
bool raisearmbtnpressed = false;
bool intakebtnpressed = false;
bool debugautobtnpressed = false;
bool waitbtnpressed = false;
bool grabbtnpressed = false;
bool secondaryuppressed = false;
//mobileloader
bool loaderexpanded = false;

//reverse
bool reversed = false;

bool lifted = false;

int leftpos = 0;
int rightpos = 0;

int mainpos = 0;
int secondarypos = 0;
int elbowpos = 0;
int intakepos = 0;
int elbowpotpos = 0;
int lastelbowpos = 0;
float elbowang = 0;
float lastelbowang = 0;

float goalelbow = 0;
float goalintake = 0;
float goalelbowang = 0;

void unloadcone(int num);
void waitingpos();
void grab();
void manualgrab();
void liftup();
void liftdown();


void intake()
{
	motor[mobileloader1] = -100;
	motor[mobileloader2] = -100;
	while(SensorValue[intaketouch] == 0);
	motor[mobileloader1] = 0;
	motor[mobileloader2] = 0;
}

void outthrow()
{
	motor[mobileloader1] = 100;
	motor[mobileloader2] = 100;
	while(SensorValue[expandtouch] == 0);
	motor[mobileloader1] = 0;
	motor[mobileloader2] = 0;
}

void skiddrive()
{
	leftspeed = -y1 - x1;
	rightspeed = -y1 + x1;
	if (reversed)
	{
		leftspeed = -y1 + x1;
		rightspeed = -y1 - x1;
	}
}

void go()
{
	motor[left] = leftspeed;
	motor[right] = rightspeed;
}

void filterRT()
{
	y1 = vexRT[Ch4];
	x1 = vexRT[Ch3];
	y2 = vexRT[Ch2];
	x2 = vexRT[Ch1];
	if(abs(x1) <= joystickthreshold)
	{
		x1 = 0;
	}
	if(abs(y1) <= joystickthreshold)
	{
		y1 = 0;
	}
	if(abs(x2) <= joystickthreshold)
	{
		x2 = 0;
	}
	if(abs(y2) <= joystickthreshold)
	{
		y2 = 0;
	}
}

bool handlebutton(TVexJoysticks vexbtn, bool &lastbtn)
{
	bool thisbtn = (vexRT[vexbtn] == 1);
	if(lastbtn){
		if (!thisbtn){
			lastbtn = thisbtn;
			return true;
		}
	}
	return false;
}

void buttonhandler2()
{
	raisearmbtnpressed = handlebutton(Btn5U, lastraisearmbtn);
	intakebtnpressed = handlebutton(Btn6U, lastintakebtn);
	debugautobtnpressed = handlebutton(Btn7L, lastdebugautobtn);
	waitbtnpressed = handlebutton(Btn8U, lastwaitbtn);
	grabbtnpressed = handlebutton(Btn8R, lastgrabbtn);
}

void buttonhandler()
{
	bool thisraisearm = (vexRT[Btn5U] == 1);
	bool thisintake = (vexRT[Btn6U] == 1);
	bool thisdebugauto = (vexRT[Btn7L] == 1);
	bool thiswait = (vexRT[Btn8U] == 1);
	bool thisgrab = (vexRT[Btn8R] == 1);
	bool thissecondaryup = (vexRT[Btn8D] == 1);
	if(lastraisearmbtn){
		if(!thisraisearm){
			raisearmbtnpressed = true;
		}
	}
	if(lastintakebtn){
		if(!thisintake){
			intakebtnpressed = true;
		}
	}
	if(lastdebugautobtn){
		if(!thisdebugauto){
			debugautobtnpressed = true;
		}
	}
	if(lastwaitbtn){
		if(!thiswait){
			waitbtnpressed = true;
		}
	}
	if(lastgrabbtn){
		if(!thisgrab){
			grabbtnpressed = true;
		}
	}
	if(lastsecondaryupbtn){
		if(!thissecondaryup){
			secondaryuppressed = true;
		}
	}
	lastraisearmbtn = thisraisearm;
	lastintakebtn = thisintake;
	lastdebugautobtn = thisdebugauto;
	lastwaitbtn = thiswait;
	lastgrabbtn = thisgrab;
	lastsecondaryupbtn = thissecondaryup;
}

void driverControl()
{
	buttonhandler();
	if(raisearmbtnpressed)
	{
		raisearmbtnpressed = false;
		unloadcone(1);
	}
	if(intakebtnpressed)
	{
		intakebtnpressed = false;
		if(loaderexpanded)
		{
			intake();
			loaderexpanded = false;
		}
		else
		{
			outthrow();
			loaderexpanded = true;
		}
	}
	if(debugautobtnpressed)
	{
		debugautobtnpressed = false;
		reversed = !reversed;
	}
	if(waitbtnpressed)
	{
		waitbtnpressed = false;
		waitingpos();
	}
	if(grabbtnpressed)
	{
		grabbtnpressed = false;
		grab();
	}
	if(secondaryuppressed)
	{
		if(lifted){
		liftdown();
		}else{
		liftup();
		}
		lifted = !lifted;
		secondaryuppressed = false;
	}
	filterRT();
	skiddrive();
	manualgrab();
}

void debugreader()
{
	leftpos = getMotorEncoder(left);
	rightpos = getMotorEncoder(right);
	mainpos = SensorValue[mainliftpot];
	secondarypos = SensorValue[secondaryliftpot];
	elbowpos = getMotorEncoder(elbow);
	intakepos = SensorValue[intakelevelpot];
	elbowpotpos = SensorValue[elbowpot];
	elbowang = 90*elbowpos/720;
	goalintake = -elbowpotpos + 3500;
	if(elbowpos > 740)
	{
//		motor[elbow] = 50;
	}
	else if (elbowpos < -300)
	{
//		motor[elbow] = -50;
	}
	else
	{
//		motor[elbow] = y2;
	}
	if(goalintake - intakepos > 200){
		motor[intakelevel] = -100;
	}
	else if(goalintake - intakepos < -200){
		motor[intakelevel] = 100;
	}else{
		motor[intakelevel] = -(goalintake - intakepos)/4;
	}
//	setMotorTarget(elbow, goalelbow, 50, true);

	lastelbowpos = elbowpos;
	lastelbowang = elbowang;
}

void autolevel()
{
	intakepos = SensorValue[intakelevelpot];
	goalintake = 2.049*elbowpos + 1100;
	if(goalintake - intakepos > 200){
		motor[intakelevel] = -100;
	}
	else if(goalintake - intakepos < -200){
		motor[intakelevel] = 100;
	}else{
		motor[intakelevel] = -(goalintake - intakepos)/4;
	}
}

void startup()
{
	mainpos = SensorValue[mainliftpot];
	secondarypos = SensorValue[secondaryliftpot];
	elbowpos = getMotorEncoder(elbow);
	intakepos = SensorValue[intakelevelpot];
	while(SensorValue[mainliftpot] > 3080)
	{
		motor[mainlift] = 100;
	}
	motor[mainlift] = 0;
	outthrow();
}

void unloadcone(int num)
{
	if(num == 1)
	{
		while(SensorValue[secondaryliftpot] > 250)
		{
			motor[secondarylift] = 50;
			autolevel();
		}
		motor[secondarylift] = 0;
		int starttime = time1[T1];
		while(SensorValue[mainliftpot] > 2485 && (time1[T1] -starttime < 3000))
		{
			motor[mainlift] = 100;
			autolevel();
		}
		motor[mainlift] = 0;
		starttime = time1[T1];
		elbowpos = getMotorEncoder(elbow);
		while(SensorValue[elbowpot] < 2600 && (time1[T1] -starttime < 3000))
		{
			motor[elbow] = 100;
			autolevel();
		}
		motor[elbow] = 0;
		starttime = time1[T1];
		while(SensorValue[mainliftpot] < 3200 && (time1[T1] - starttime < 3000))
		{
			motor[mainlift] = -100;
			autolevel();
		}
		motor[mainlift] = 0;
		while(SensorValue[elbowpot] > 1890)
		{
			elbowpos = getMotorEncoder(elbow);
			motor[elbow] = -100;
			autolevel();
		}
		motor[elbow] = 0;
	}
	waitingpos();
	num++;
}

void waitingpos()
{
	while(SensorValue[mainliftpot] > 2875)
		{
			motor[mainlift] = 100;
			autolevel();
		}
		motor[mainlift] = 0;
		while(SensorValue[secondaryliftpot] < 3875)
		{
			motor[secondarylift] = -100;
			autolevel();
		}
		motor[secondarylift] = 0;
		while(SensorValue[elbowpot] > 1600)
		{
			motor[elbow] = -50;
			autolevel();
		}
		motor[elbow] = 0;
}

void manualgrab()
{
	motor[elbow] = -x2/2;
	motor[mainlift] = y2/2;
}

void grab()
{
	waitingpos();
	while(elbowpotpos > 1600)
	{
		elbowpotpos = SensorValue[elbowpot];
		elbowpos = getMotorEncoder(elbow);
			motor[elbow] = -50;
			autolevel();
		}
	motor[elbow] = 0;
	int starttime = time1[T1];
	while(time1[T1] - starttime < 1000)
	{
		elbowpotpos = SensorValue[elbowpot];
		elbowpos = getMotorEncoder(elbow);
		if(elbowpotpos >1600){
			motor[elbow] = -50;
		}else{
			motor[elbow] = 0;
		}
		autolevel();
	}
	starttime = time1[T1];
	while((SensorValue[mainliftpot] < 3800)&& (time1[T1]-starttime < 1000))
		{
			elbowpos = getMotorEncoder(elbow);
			elbowpotpos = SensorValue[elbowpot];
			if(elbowpotpos > 1600)
			{
				motor[elbow] = -50;
			}else{
				motor[elbow] = 0;
			}
			motor[mainlift] = -100;
			autolevel();
		}
	delay(1000);
	motor[mainlift] = 0;
	motor[elbow] = 0;
	while(elbowpotpos > 1400)
	{
		elbowpotpos = SensorValue[elbowpot];
		elbowpos = getMotorEncoder(elbow);
			motor[elbow] = -50;
			autolevel();
		}
	motor[elbow] = 0;
	while(SensorValue[mainliftpot] > 3080 || SensorValue[secondaryliftpot] > 250)
	{
		if(SensorValue[elbowpot] < 1400)
		{
			motor[elbow] = 50;
		}else{
			motor[elbow] = 0;
		}
		if(SensorValue[mainliftpot] > 3080){
			motor[mainlift] = 100;
		}else{
			motor[mainlift] = 0;
		}
		if(SensorValue[secondaryliftpot] > 250)
		{
			motor[secondarylift] = 50;
		}else{
			motor[secondarylift] = 0;
		}
		autolevel();
	}
	motor[mainlift] = 0;
	unloadcone(1);
}

void liftup()
{
	while(SensorValue[secondaryliftpot] > 250){
		motor[secondarylift] = 100;
			autolevel();
		}
		motor[secondarylift] = 0;
}

void liftdown()
{
			while(SensorValue[secondaryliftpot] < 3875)
		{
			motor[secondarylift] = -100;
			autolevel();
		}
		motor[secondarylift] = 0;
}

void autostart()
{
	setMotorTarget(left, 1750, 100, false);
	setMotorTarget(right, 1750, 100, false);
	while(!(getMotorEncoder(left) && getMotorEncoder(right)));
	intake();
	unloadcone(1);
	setMotorTarget(left, 0, 100, false);
	setMotorTarget(right, 0, 100, false);
	while(!(getMotorEncoder(left) && getMotorEncoder(right)));
}

task main()
{
	resetMotorEncoder(elbow);
	resetMotorEncoder(left);
	resetMotorEncoder(right);
	startup();
	autostart();
	while(1)
	{
		debugreader();
//		autolevel();
		driverControl();
		go();
	}
}
