#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl1,  ,               sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  ,               sensorQuadEncoder)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port2,           left,          tmotorVex393_MC29, PIDControl, driveLeft, encoderPort, I2C_1)
#pragma config(Motor,  port3,           right,         tmotorVex393_MC29, PIDControl, reversed, driveRight, encoderPort, I2C_2)
#pragma config(Motor,  port4,           mainlift,      tmotorVex393_MC29, PIDControl, encoderPort, dgtl1)
#pragma config(Motor,  port5,           intakelevel,   tmotorVex393_MC29, PIDControl, encoderPort, dgtl3)
#pragma config(Motor,  port6,           mobileloader1, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           mobileloader2, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           elbow,         tmotorVex393_MC29, PIDControl, encoderPort, I2C_3)
#pragma config(Motor,  port9,           secondarylift, tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define raisearmbtn vexRT[Btn5U]
#define intakebtn vexRT[Btn6U]
#define debugautobtn vexRT[Btn7L]

#define joystickthreshold 15
#define mobileloaderdelay 50

int leftspeed;
int rightspeed;

int x1;
int y1;
int x2;
int y2;

//Last button state
bool lastraisearmbtn = false;
bool lastintakebtn = false;
bool lastdebugautobtn = false;

//Button press
bool raisearmbtnpressed = false;
bool intakebtnpressed = false;
bool debugautobtnpressed = false;

//mobileloader
bool loaderexpanded = false;

void intake()
{
	motor[mobileloader1] = 100;
	motor[mobileloader2] = 100;
	delay(mobileloaderdelay);
}

void outthrow()
{
	motor[mobileloader1] = -100;
	motor[mobileloader2] = -100;
	delay(mobileloaderdelay);
}

void skiddrive()
{
	leftspeed = x1 + y1;
	rightspeed = x1 - y1;
}

void go()
{
	motor[left] = leftspeed;
	motor[right] = rightspeed;
}

void filterRT()
{
	x1 = vexRT[Ch4];
	y1 = vexRT[Ch3];
	x2 = vexRT[Ch2];
	y2 = vexRT[Ch1];
	if(abs(x1) <= joystickthreshold)
	{
		x1 = 0;
	}
	if(abs(y1) <= joystickthreshold)
	{
		y1 = 0;
	}
	if(abs(x2) <= joystickthreshold)
	{
		x2 = 0;
	}
	if(abs(y2) <= joystickthreshold)
	{
		y2 = 0;
	}
}

void buttonhandler()
{
	bool thisraisearm = (vexRT[Btn5U] == 1);
	bool thisintake = (vexRT[Btn6U] == 1);
	bool thisdebugauto = (vexRT[Btn7L] == 1);
	if(lastraisearmbtn){
		if(!thisraisearm){
			raisearmbtnpressed = true;
		}
	}
	if(lastintakebtn){
		if(!thisintake){
			intakebtnpressed = true;
		}
	}
	if(lastdebugautobtn){
		if(!thisdebugauto){
			debugautobtnpressed = true;
		}
	}
	lastraisearmbtn = thisraisearm;
	lastintakebtn = thisintake;
	lastdebugautobtn = thisdebugauto;
}

void driverControl()
{
	buttonhandler();
	if(raisearmbtnpressed)
	{
		raisearmbtnpressed = false;
	}
	if(intakebtnpressed)
	{
		intakebtnpressed = false;
		if(loaderexpanded)
		{
			intake();
		}
		else
		{
			outthrow();
		}
		loaderexpanded = !loaderexpanded;
	}
	if(debugautobtnpressed)
	{
		debugautobtnpressed = false;
	}
	filterRT();
	skiddrive();
}

task main()
{
	while(1)
	{
		driverControl();
		go();
	}
}
